plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline
app: social-serveless
service: social-serveless
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: ${env:REGION}
  timeout: 30
  memorySize: 256
  iamRoleStatements: ${file(./sls-yml/iamRoleStatements.yml)}
  environment: ${file(./sls-yml/environment.yml)}
  httpApi:
    authorizers:
      verifyToken:
        type: request
        name: verifyToken
        identitySource: $request.header.cookie

custom: ${file(./sls-yml/custom.yml)}

resources: ${file(./sls-yml/resources.yml)}

functions: ${file(./sls-yml/functions.yml)}
