plugins:
  - serverless-dynamodb-local
  - serverless-offline-s3
  - serverless-offline
  - serverless-functions-base-path

org: janisrasins
app: social-serveless
service: social-serveless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1
  memorySize: 256
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-central-1:*:*"
        - Effect: Allow
          Action: "s3:ListBucket" # Allow functions to list all buckets
          Resource: "*"
        - Effect: Allow
          Action: # Allow functions to read/write objects in a bucket
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::social-net/*"
  environment: ${file(./config/environment.yml)}

custom: ${file(./config/custom.yml)}

resources: ${file(./config/resources.yml)}

functions: ${file(./config/functions.yml)}
