SERVERLESS_REGION: eu-central-1
SERVERLESS_ENDPOINT: http://localhost:8010
SERVERLESS_TABLE_SOCIAL_USERS: social_users
SERVERLESS_TABLE_SOCIAL_POSTS: social_posts
SERVERLESS_TABLE_SOCIAL_MESSAGES: social_messages
SERVERLESS_TABLE_SOCIAL_AUTH: social_auth
