hello-world:
  handler: handler.handle # required, handler set in AWS Lambda
  name: "${self:service}-${self:provider.stage}" # optional, Deployed Lambda name
  description: "slspress offline example"
  events:
    - http:
        path: hello-world
        method: get
        cors: true
createUser:
  handler: users.createUser
  events:
    - http:
        path: users
        method: POST
getUsers:
  handler: users.getUsers
  events:
    - http:
        path: users
        method: GET
deleteUser:
  handler: users.deleteUser
  events:
    - http:
        path: users
        method: DELETE
