hello-world:
  handler: handler.handle # required, handler set in AWS Lambda
  name: "${self:service}-${self:provider.stage}" # optional, Deployed Lambda name
  description: "slspress offline example"
  events:
    - http:
        path: hello-world
        method: get
        cors: true
createUser:
  handler: users.createUser
  events:
    - http:
        path: users/create
        method: POST
getUsers:
  handler: users.getUsers
  events:
    - http:
        path: users
        method: GET
deleteUser:
  handler: users.deleteUser
  events:
    - http:
        path: users
        method: DELETE
getPosts:
  handler: posts.getPosts
  events:
    - http:
        path: posts
        method: GET
createPost:
  handler: posts.createPost
  events:
    - http:
        path: posts/create
        method: POST
getMessages:
  handler: messages.getMessages
  events:
    - http:
        path: messages
        method: GET
createMessage:
  handler: messages.createMessage
  events:
    - http:
        path: messages/create
        method: POST
