# CloudFormation template syntax
Resources:
  socialUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: social_users
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  socialPosts:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: social_posts
      AttributeDefinitions:
        - AttributeName: postsId
          AttributeType: N
        - AttributeName: unixTimestamp
          AttributeType: N
      KeySchema:
        - AttributeName: postsId
          KeyType: HASH
        - AttributeName: unixTimestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  socialMessages:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: social_messages
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: N
        - AttributeName: unixTimestamp
          AttributeType: N
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
        - AttributeName: unixTimestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  socialAuth:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: social_auth
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: N
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
